name: File to envs

on:
  push

jobs:
  FileToEnvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: File to envs
        run: |
          echo -e ${{ secrets.ENVS_CONTENT }} > secrets.txt
          source secrets.txt && export $(sed '/^#/d' secrets.txt | cut -d= -f1)

      - name: Upload Artifact      
        uses: actions/upload-artifact@v3
        with:
          name: secrets_from_envs
          path: "secrets.txt"
