name: File to envs

on:
  push

jobs:
  FileToEnvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: File to envs
        run: |
          source ${{ secrets.ENVS_CONTENT }} && export $(sed '/^#/d' ${{ secrets.ENVS_CONTENT }} | cut -d= -f1)
      
      - run: echo "$GITHUB_CONTEXT"
