name: File to envs

on:
  push

jobs:
  FileToEnvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Echo in file"
        env:
          SECRETS_VARS: ${{ toJson(secrets.ENVS_CONTENT) }}
        run: echo "$SECRETS_VARS" > "secrets.txt"
      
      # - name: File to envs
      #   run: |
      #     source secrets.txt && export $(sed '/^#/d' secrets.txt | cut -d= -f1)

      - name: Upload Artifact      
        uses: actions/upload-artifact@v3
        with:
          name: secrets_from_envs
          path: "secrets.txt"
