name: File to envs

on:
  push

jobs:
  FileToEnvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: File to envs
        run: |
          echo ${{ secrets.ENVS_CONTENT }} > secrets.txt
          source secrets.txt && export $(sed '/^#/d' secrets.txt | cut -d= -f1)
      
      - run: echo "$GITHUB_CONTEXT"
